---

- hosts: all
  become: yes
  gather_facts: false
  roles:
    - { role: ansible-nrpe, nagios_ip: "100.127.173.128"}

- hosts: all
  become: yes
  gather_facts: true
  roles:
    - { role: ansible-docker }

#- hosts: localhost
#  gather_facts: true
#  tasks:
#    - name: Install jq
#      apt:
#        name: jq
#        state: present
#      tags: vips

#    - name: Gather VIP associated with host {{ inventory_hostname }}
#      raw: neutron port-show $(neutron port-list -f csv| grep 100.127.165.132 | cut -d\" -f2) -f json | jq '.allowed_address_pairs | .[] | .ip_address'
#      register: vips
#      tags: vips

#    - name: debug
#      debug: msg="{{ vips.stdout }}"
#      tags: vips
